# Generated by Django 5.0.4 on 2024-04-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_user_date_joined_user_first_name_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
