# Generated by Django 5.0.4 on 2024-04-14 04:52

import authuser.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authuser.models.CustomUserManager()),
            ],
        ),
    ]
