# Generated by Django 5.0.4 on 2024-04-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('role', models.CharField(choices=[('REC', 'Recruiter'), ('APP', 'Applicant')], default='APP', max_length=50)),
            ],
        ),
    ]
