# Generated by Django 5.0.4 on 2024-04-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeRaterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Recruiter', 'REC'), ('Applicant', 'APP')], default='Applicant', max_length=50),
        ),
    ]
