# Generated by Django 5.0.4 on 2024-04-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeRaterApp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
