# Generated by Django 5.0.4 on 2024-04-16 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ResumeRaterApp", "0005_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobs", options={"verbose_name": "Job", "verbose_name_plural": "Jobs"},
        ),
        migrations.AlterField(
            model_name="jobs",
            name="jobDescription",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="recruiter",
            field=models.ForeignKey(
                limit_choices_to={"role": "REC"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="applicant",
            field=models.ForeignKey(
                limit_choices_to={"role": "APP"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
